-- Migration 003: Add description column to metrics and populate clinical explanations
-- Safe to run multiple times (ADD COLUMN IF NOT EXISTS + WHERE description IS NULL).

ALTER TABLE metrics ADD COLUMN IF NOT EXISTS description TEXT;

-- Populate descriptions for all known metrics (only sets where currently NULL).
-- Sources: standard clinical reference ranges and medical definitions.

UPDATE metrics SET description = 'White Blood Cell count — total immune cells circulating in blood; elevated in infection or inflammation, low in bone marrow suppression or severe viral illness.' WHERE name = 'WBC' AND description IS NULL;
UPDATE metrics SET description = 'Red Blood Cell count — oxygen-carrying cells in blood; low count indicates anemia, high count seen in dehydration or polycythemia.' WHERE name = 'RBC' AND description IS NULL;
UPDATE metrics SET description = 'Protein inside red blood cells that binds and transports oxygen; the primary marker for anemia — low in iron deficiency, chronic disease, or blood loss.' WHERE name = 'Hemoglobin' AND description IS NULL;
UPDATE metrics SET description = 'Percentage of blood volume made up of red blood cells; parallels hemoglobin and is used to classify anemia severity.' WHERE name = 'Hematocrit' AND description IS NULL;
UPDATE metrics SET description = 'Cell fragments that clump together to form clots and stop bleeding; low count (thrombocytopenia) raises bleeding risk, high count raises clotting risk.' WHERE name = 'Platelets' AND description IS NULL;
UPDATE metrics SET description = 'Mean Corpuscular Volume — average size of a red blood cell; helps classify anemia type: low = microcytic (iron deficiency), high = macrocytic (B12/folate deficiency).' WHERE name = 'MCV' AND description IS NULL;
UPDATE metrics SET description = 'Mean Corpuscular Hemoglobin — average amount of hemoglobin per red blood cell; decreases in iron deficiency and thalassemia.' WHERE name = 'MCH' AND description IS NULL;
UPDATE metrics SET description = 'Mean Corpuscular Hemoglobin Concentration — hemoglobin concentration relative to RBC size; very low in iron deficiency, slightly low in thalassemia.' WHERE name = 'MCHC' AND description IS NULL;
UPDATE metrics SET description = 'Red Cell Distribution Width — variation in RBC size; elevated when multiple anemia types coexist or in early iron/B12 deficiency before MCV changes.' WHERE name = 'RDW' AND description IS NULL;
UPDATE metrics SET description = 'Mean Platelet Volume — average size of platelets; large platelets indicate rapid bone marrow production, often seen after platelet destruction or major bleeding.' WHERE name = 'MPV' AND description IS NULL;

UPDATE metrics SET description = 'Absolute Neutrophil Count — primary bacteria-fighting white cells; the ANC is the key number for infection risk — below 1.0 is clinically significant.' WHERE name = 'Abs Neutrophils' AND description IS NULL;
UPDATE metrics SET description = 'Absolute Lymphocyte Count — B cells and T cells combined; low in viral illness, HIV, or immunosuppressive therapy; elevated in viral infections and some leukemias.' WHERE name = 'Abs Lymphocytes' AND description IS NULL;
UPDATE metrics SET description = 'Absolute Monocyte Count — precursors to tissue macrophages; elevated in chronic infections, inflammatory conditions, and some hematologic malignancies.' WHERE name = 'Abs Monocytes' AND description IS NULL;
UPDATE metrics SET description = 'Absolute Eosinophil Count — cells involved in allergic responses and parasite defense; elevated in asthma, allergies, eczema, or parasitic infection.' WHERE name = 'Abs Eosinophils' AND description IS NULL;
UPDATE metrics SET description = 'Absolute Basophil Count — the rarest white blood cell; involved in allergic reactions; rarely elevated except in myeloproliferative disorders.' WHERE name = 'Abs Basophils' AND description IS NULL;
UPDATE metrics SET description = 'Absolute Immature Granulocyte Count — bands and metamyelocytes released early from bone marrow; elevated during severe infection or bone marrow stress.' WHERE name = 'Abs Immature Granulocytes' AND description IS NULL;

UPDATE metrics SET description = 'Neutrophils as a percentage of total WBCs; elevated in bacterial infections (>70%), low in viral illness. Does not indicate absolute count — use ANC for infection risk.' WHERE name = 'Neutrophils %' AND description IS NULL;
UPDATE metrics SET description = 'Lymphocytes as a percentage of total WBCs; elevated in viral infections and chronic lymphocytic leukemia; low in HIV, steroid use, or immunosuppression.' WHERE name = 'Lymphocytes %' AND description IS NULL;
UPDATE metrics SET description = 'Monocytes as a percentage of total WBCs; elevated in chronic inflammation, tuberculosis, and some autoimmune conditions.' WHERE name = 'Monocytes %' AND description IS NULL;
UPDATE metrics SET description = 'Eosinophils as a percentage of total WBCs; elevated in allergic diseases, asthma, and parasitic infections.' WHERE name = 'Eosinophils %' AND description IS NULL;
UPDATE metrics SET description = 'Basophils as a percentage of total WBCs; rarely elevated; may be seen in allergic reactions or myeloproliferative disorders.' WHERE name = 'Basophils %' AND description IS NULL;
UPDATE metrics SET description = 'Immature Granulocytes as a percentage of total WBCs; presence suggests the bone marrow is releasing cells prematurely due to high demand.' WHERE name = 'Immature Granulocytes %' AND description IS NULL;

UPDATE metrics SET description = 'Fasting blood sugar — the primary screen for diabetes and prediabetes; normal fasting: 70–99 mg/dL, prediabetes: 100–125 mg/dL, diabetes: ≥126 mg/dL on two occasions.' WHERE name = 'Glucose' AND description IS NULL;
UPDATE metrics SET description = 'Blood Urea Nitrogen — a protein metabolism waste product filtered by the kidneys; elevated when kidney filtration declines or protein intake/catabolism is very high.' WHERE name = 'BUN' AND description IS NULL;
UPDATE metrics SET description = 'Muscle metabolism waste product; the standard marker of kidney filtration — even small increases are clinically meaningful; used to calculate eGFR.' WHERE name = 'Creatinine' AND description IS NULL;
UPDATE metrics SET description = 'Estimated Glomerular Filtration Rate — calculated estimate of how much blood the kidneys filter per minute; declines with chronic kidney disease; <60 for >3 months = CKD.' WHERE name = 'eGFR' AND description IS NULL;
UPDATE metrics SET description = 'The primary electrolyte controlling fluid balance; abnormal levels (hypo- or hypernatremia) indicate hydration problems, adrenal disorders, or SIADH.' WHERE name = 'Sodium' AND description IS NULL;
UPDATE metrics SET description = 'Critical electrolyte for heart rhythm and muscle contraction; both high (hyperkalemia) and low (hypokalemia) levels can cause dangerous cardiac arrhythmias.' WHERE name = 'Potassium' AND description IS NULL;
UPDATE metrics SET description = 'Major electrolyte that helps maintain fluid balance and acid-base equilibrium; moves inversely with bicarbonate; abnormal in GI losses or kidney disease.' WHERE name = 'Chloride' AND description IS NULL;
UPDATE metrics SET description = 'Bicarbonate level in blood — the metabolic component of acid-base balance; low in metabolic acidosis (diabetic ketoacidosis, renal failure), high in metabolic alkalosis.' WHERE name = 'CO2' AND description IS NULL;
UPDATE metrics SET description = 'Mineral essential for bone strength, nerve signaling, muscle contraction, and blood clotting; regulated by parathyroid hormone and vitamin D.' WHERE name = 'Calcium' AND description IS NULL;
UPDATE metrics SET description = 'Calculated gap between measured cations and anions; elevated anion gap indicates metabolic acidosis from ketones, lactate, uremia, or toxins (MUDPILES mnemonic).' WHERE name = 'Anion Gap' AND description IS NULL;

UPDATE metrics SET description = 'Alanine Aminotransferase — liver-specific enzyme released when hepatocytes are damaged; the most sensitive and specific blood marker for liver cell injury.' WHERE name = 'ALT' AND description IS NULL;
UPDATE metrics SET description = 'Aspartate Aminotransferase — enzyme in liver, heart, and skeletal muscle; less liver-specific than ALT; AST:ALT ratio >2 suggests alcoholic liver disease.' WHERE name = 'AST' AND description IS NULL;
UPDATE metrics SET description = 'Alkaline Phosphatase — enzyme in liver (bile ducts) and bone; elevated when bile flow is obstructed or during rapid bone turnover (growth, fracture healing, Paget''s disease).' WHERE name = 'Alk Phos' AND description IS NULL;
UPDATE metrics SET description = 'Total Bilirubin — yellow pigment from red blood cell breakdown; elevated bilirubin causes jaundice; rises in liver disease, bile duct obstruction, or hemolysis.' WHERE name = 'Total Bilirubin' AND description IS NULL;
UPDATE metrics SET description = 'Direct (conjugated) bilirubin — bilirubin that has been processed by the liver; selectively elevated in bile duct obstruction or intrahepatic cholestasis.' WHERE name = 'Direct Bilirubin' AND description IS NULL;
UPDATE metrics SET description = 'Gamma-Glutamyl Transferase — enzyme highly sensitive to liver stress and alcohol consumption; useful for confirming a hepatic source of elevated Alk Phos.' WHERE name = 'GGT' AND description IS NULL;
UPDATE metrics SET description = 'Major blood protein synthesized by the liver; reflects liver synthetic function and nutritional status; low in chronic liver disease, malnutrition, or inflammation.' WHERE name = 'Albumin' AND description IS NULL;
UPDATE metrics SET description = 'Sum of albumin and globulins in plasma; reflects overall nutritional status, liver synthetic function, and immune activity.' WHERE name = 'Total Protein' AND description IS NULL;
UPDATE metrics SET description = 'Total Protein minus Albumin; includes immunoglobulins and other proteins; elevated in chronic infections, autoimmune disease, or multiple myeloma.' WHERE name = 'Globulin' AND description IS NULL;
UPDATE metrics SET description = 'Albumin-to-Globulin ratio; normally >1; reversed ratio (A/G <1) seen in liver disease, nephrotic syndrome, or conditions with excess immunoglobulin production.' WHERE name = 'A/G Ratio' AND description IS NULL;

UPDATE metrics SET description = 'Total cholesterol in all lipoprotein particles; a general cardiovascular risk indicator; optimal <200 mg/dL, but LDL and non-HDL are better risk predictors.' WHERE name = 'Total Cholesterol' AND description IS NULL;
UPDATE metrics SET description = '"Good" cholesterol — transports cholesterol from arteries back to the liver; higher HDL is protective; low HDL (<40 men, <50 women) is an independent cardiovascular risk factor.' WHERE name = 'HDL Cholesterol' AND description IS NULL;
UPDATE metrics SET description = '"Bad" cholesterol — deposits cholesterol in arterial walls driving atherosclerosis; primary treatment target; optimal <100 mg/dL, <70 mg/dL in high-risk individuals.' WHERE name = 'LDL Cholesterol' AND description IS NULL;
UPDATE metrics SET description = 'Blood fats derived from diet and liver synthesis; elevated in metabolic syndrome, diabetes, excess alcohol, and hypothyroidism; optimal <150 mg/dL.' WHERE name = 'Triglycerides' AND description IS NULL;
UPDATE metrics SET description = 'Total Cholesterol minus HDL — all cholesterol carried in atherogenic particles (LDL, VLDL, IDL); a strong predictor of cardiovascular risk; target <130 mg/dL.' WHERE name = 'Non-HDL Cholesterol' AND description IS NULL;
UPDATE metrics SET description = 'Protein that forms the outer shell of LDL particles; each LDL particle contains exactly one ApoB; may predict cardiovascular risk better than LDL-C in insulin resistance.' WHERE name = 'Apolipoprotein B' AND description IS NULL;
UPDATE metrics SET description = 'Ratio of total cholesterol to HDL; integrates both atherogenic and protective cholesterol; target <5, optimal <3.5. Higher ratio = higher cardiovascular risk.' WHERE name = 'Cholesterol/HDL Ratio' AND description IS NULL;

UPDATE metrics SET description = 'Thyroid Stimulating Hormone — pituitary signal that controls thyroid gland output; the single best screen for thyroid disease; elevated = hypothyroidism, suppressed = hyperthyroidism.' WHERE name = 'TSH' AND description IS NULL;
UPDATE metrics SET description = 'Free Thyroxine — the main circulating thyroid hormone (unbound fraction); measured with TSH to diagnose and manage hypothyroidism and hyperthyroidism.' WHERE name = 'Free T4' AND description IS NULL;
UPDATE metrics SET description = 'Free Triiodothyronine — the biologically active form of thyroid hormone; T4 is converted to T3 in tissues; useful in monitoring hyperthyroidism treatment.' WHERE name = 'Free T3' AND description IS NULL;
UPDATE metrics SET description = 'Total Thyroxine (bound + free); affected by binding protein changes (pregnancy, oral contraceptives); Free T4 is preferred for diagnosing thyroid disorders.' WHERE name = 'T4 Total' AND description IS NULL;
UPDATE metrics SET description = 'Total Triiodothyronine (bound + free); occasionally useful in T3 toxicosis; Free T3 is generally preferred for clinical management.' WHERE name = 'T3 Total' AND description IS NULL;

UPDATE metrics SET description = 'Cardiac-specific protein released when heart muscle cells die; the gold standard biomarker for diagnosing myocardial infarction; even small elevations are significant.' WHERE name = 'Troponin I' AND description IS NULL;
UPDATE metrics SET description = 'Creatine Kinase — enzyme found in muscle cells; elevated when muscle is damaged; total CK rises in both cardiac and skeletal muscle injury.' WHERE name = 'CK' AND description IS NULL;
UPDATE metrics SET description = 'CK isoenzyme specific to heart muscle; elevated in myocardial infarction; largely replaced by troponin for cardiac diagnosis but still used in some protocols.' WHERE name = 'CK-MB' AND description IS NULL;
UPDATE metrics SET description = 'B-type Natriuretic Peptide — hormone released by heart ventricles under pressure overload; the primary blood test for diagnosing and monitoring heart failure severity.' WHERE name = 'BNP' AND description IS NULL;

UPDATE metrics SET description = 'Iron storage protein in cells; the most sensitive indicator of iron stores — low ferritin = iron deficiency even before anemia develops; elevated in inflammation (acute phase reactant).' WHERE name = 'Ferritin' AND description IS NULL;
UPDATE metrics SET description = 'Serum iron — iron being transported in blood bound to transferrin; low in iron deficiency and chronic disease, high in iron overload (hemochromatosis).' WHERE name = 'Iron' AND description IS NULL;
UPDATE metrics SET description = 'Total Iron Binding Capacity — reflects the total amount of transferrin available to carry iron; elevated in iron deficiency (the body upregulates transport capacity).' WHERE name = 'TIBC' AND description IS NULL;
UPDATE metrics SET description = 'Transferrin Saturation — percentage of transferrin currently bound with iron (Iron / TIBC × 100); low in iron deficiency, high in iron overload; <20% suggests deficiency.' WHERE name = 'Transferrin Saturation' AND description IS NULL;

UPDATE metrics SET description = 'Prothrombin Time — measures speed of the extrinsic clotting pathway; prolonged in warfarin use, liver disease, vitamin K deficiency, or disseminated intravascular coagulation.' WHERE name = 'PT' AND description IS NULL;
UPDATE metrics SET description = 'Partial Thromboplastin Time — measures the intrinsic clotting pathway; prolonged in hemophilia A/B, heparin therapy, antiphospholipid syndrome, or factor deficiencies.' WHERE name = 'PTT' AND description IS NULL;
UPDATE metrics SET description = 'International Normalized Ratio — standardized prothrombin time ratio; used to monitor warfarin anticoagulation (target 2–3 for most indications) and assess liver synthetic function.' WHERE name = 'INR' AND description IS NULL;
UPDATE metrics SET description = 'Clotting protein that is converted to fibrin mesh to form a stable clot; low in DIC, severe liver disease, or major bleeding; elevated as an acute phase reactant.' WHERE name = 'Fibrinogen' AND description IS NULL;

UPDATE metrics SET description = 'C-Reactive Protein — non-specific inflammation marker produced by the liver; rises rapidly within hours of inflammation, infection, or tissue damage; falls when the cause resolves.' WHERE name = 'CRP' AND description IS NULL;
UPDATE metrics SET description = 'High-Sensitivity CRP — detects lower CRP concentrations; used to predict cardiovascular risk in apparently healthy individuals; <1 = low risk, 1–3 = moderate, >3 = elevated.' WHERE name = 'hsCRP' AND description IS NULL;
UPDATE metrics SET description = 'Erythrocyte Sedimentation Rate — how quickly red blood cells fall in a tube; a non-specific indicator of inflammation, infection, autoimmune disease, or malignancy.' WHERE name = 'ESR' AND description IS NULL;
UPDATE metrics SET description = 'Interleukin-6 — pro-inflammatory cytokine driving the acute phase response; elevated in sepsis, autoimmune flares, cytokine release syndrome, and COVID-19 severe disease.' WHERE name = 'IL-6' AND description IS NULL;

UPDATE metrics SET description = 'Pancreatic hormone that lowers blood glucose by enabling cells to take up sugar; fasting hyperinsulinemia indicates insulin resistance even when glucose is still normal.' WHERE name = 'Insulin' AND description IS NULL;
UPDATE metrics SET description = 'Primary stress hormone from the adrenal cortex; regulates metabolism, immune response, and blood pressure; abnormal levels indicate adrenal or pituitary disorders.' WHERE name = 'Cortisol' AND description IS NULL;
UPDATE metrics SET description = 'Adrenocorticotropic Hormone — pituitary hormone that stimulates cortisol production; measured alongside cortisol to locate the source of adrenal dysfunction (central vs adrenal).' WHERE name = 'ACTH' AND description IS NULL;

UPDATE metrics SET description = 'Fat-soluble vitamin critical for calcium absorption, bone mineralization, and immune regulation; widespread deficiency worldwide; optimal 40–80 ng/mL for most adults.' WHERE name = 'Vitamin D' AND description IS NULL;
UPDATE metrics SET description = 'Essential vitamin for DNA synthesis, myelin sheath maintenance, and red blood cell production; deficiency causes megaloblastic anemia and peripheral neuropathy.' WHERE name = 'Vitamin B12' AND description IS NULL;
UPDATE metrics SET description = 'B vitamin (folate) required for DNA synthesis and cell division; deficiency causes megaloblastic anemia and neural tube defects in early pregnancy.' WHERE name = 'Folate' AND description IS NULL;

UPDATE metrics SET description = 'Hemoglobin A1c — reflects average blood glucose over the past 2–3 months; the primary marker for diabetes monitoring and diagnosis: <5.7% normal, 5.7–6.4% prediabetes, ≥6.5% diabetes.' WHERE name = 'Hemoglobin A1c' AND description IS NULL;
UPDATE metrics SET description = 'Lactate Dehydrogenase — enzyme released when any cells are damaged; a non-specific marker of tissue injury; elevated in hemolysis, myocardial infarction, liver disease, and cancer.' WHERE name = 'LDH' AND description IS NULL;
UPDATE metrics SET description = 'Electrolyte critical for >300 enzyme reactions, nerve transmission, and muscle function; low magnesium (hypomagnesemia) is common in alcoholism, malnutrition, and with diuretic use.' WHERE name = 'Magnesium' AND description IS NULL;
UPDATE metrics SET description = 'Free (unbound) calcium in plasma — the biologically active fraction; controlled very tightly; low ionized calcium causes tetany and cardiac arrhythmias.' WHERE name = 'Ionized Calcium' AND description IS NULL;
UPDATE metrics SET description = 'Purine breakdown product excreted by kidneys; elevated in gout (uric acid crystallizes in joints), kidney disease, or high-purine diets; also a cardiovascular risk marker.' WHERE name = 'Uric Acid' AND description IS NULL;
UPDATE metrics SET description = 'Mineral working with calcium to build bone and teeth; regulated by parathyroid hormone and vitamin D; abnormal in kidney disease, hyperparathyroidism, and malnutrition.' WHERE name = 'Phosphorus' AND description IS NULL;
UPDATE metrics SET description = 'Marker of anaerobic metabolism — produced when cells are oxygen-deprived; elevated in sepsis, cardiogenic shock, severe anemia, or intense exercise; guides critical care management.' WHERE name = 'Lactate' AND description IS NULL;

UPDATE metrics SET description = 'Percentage of lymphocytes bearing the CD3 surface marker — present on all mature T cells; the broadest measure of T cell immunity.' WHERE name = 'CD3 T Cells %' AND description IS NULL;
UPDATE metrics SET description = 'Absolute count of CD3+ T lymphocytes in blood; used to characterize immune deficiency states and monitor recovery after immunosuppressive therapy.' WHERE name = 'CD3 T Cells Abs' AND description IS NULL;
UPDATE metrics SET description = 'Helper T cells as a percentage of lymphocytes; CD4 cells coordinate immune responses; the key monitoring parameter in HIV infection.' WHERE name = 'CD4 T Cells %' AND description IS NULL;
UPDATE metrics SET description = 'Absolute CD4+ T helper cell count; the definitive marker of HIV disease progression; <200 cells/μL defines AIDS; guides antiretroviral therapy decisions.' WHERE name = 'CD4 T Cells Abs' AND description IS NULL;
UPDATE metrics SET description = 'Cytotoxic T cells as a percentage of lymphocytes; these cells directly kill virus-infected and cancer cells; elevated in acute viral infections.' WHERE name = 'CD8 T Cells %' AND description IS NULL;
UPDATE metrics SET description = 'Absolute count of CD8+ cytotoxic T lymphocytes; used alongside CD4 count to characterize immune status and monitor recovery after transplant or immunotherapy.' WHERE name = 'CD8 T Cells Abs' AND description IS NULL;
UPDATE metrics SET description = 'Ratio of helper T cells to cytotoxic T cells; normally >1; inverted ratio (<1) is characteristic of HIV infection and some other immunodeficiency states.' WHERE name = 'CD4/CD8 Ratio' AND description IS NULL;
UPDATE metrics SET description = 'B lymphocytes as a percentage of lymphocytes; B cells produce antibodies; monitored in B cell malignancies (CLL), immune deficiencies, and rituximab therapy.' WHERE name = 'CD19 B Cells %' AND description IS NULL;
UPDATE metrics SET description = 'Absolute count of CD19+ B lymphocytes; used to assess humoral immunity, monitor B cell depleting therapies, and characterize lymphoproliferative disorders.' WHERE name = 'CD19 B Cells Abs' AND description IS NULL;
UPDATE metrics SET description = 'Natural Killer cells as a percentage of lymphocytes; NK cells provide innate immunity against viruses and cancer without prior sensitization; monitored in NK cell disorders and transplantation.' WHERE name = 'CD16/CD56 NK Cells %' AND description IS NULL;

UPDATE metrics SET description = 'Measure of blood acidity; tightly regulated between 7.35–7.45; below 7.35 = acidosis (respiratory or metabolic), above 7.45 = alkalosis; life-threatening outside 6.8–7.8.' WHERE name = 'pH' AND description IS NULL;
UPDATE metrics SET description = 'Partial pressure of CO2 in blood — reflects respiratory function; elevated when breathing is insufficient (hypoventilation), low when breathing too fast (hyperventilation).' WHERE name = 'PCO2' AND description IS NULL;
UPDATE metrics SET description = 'Partial pressure of oxygen in arterial blood — reflects how well the lungs are oxygenating the blood; <60 mmHg = respiratory failure requiring supplemental oxygen.' WHERE name = 'PO2' AND description IS NULL;
UPDATE metrics SET description = 'Percentage of hemoglobin saturated with oxygen (SaO2 from blood gas, distinct from pulse oximetry SpO2); normal ≥95%; below 90% indicates significant hypoxemia.' WHERE name = 'Oxygen Saturation' AND description IS NULL;
UPDATE metrics SET description = 'Metabolic component of acid-base balance reflecting bicarbonate surplus or deficit; negative = metabolic acidosis, positive = metabolic alkalosis; normal ±2 mEq/L.' WHERE name = 'Base Excess' AND description IS NULL;

UPDATE metrics SET description = 'Calculated ratio (BUN / creatinine) used to distinguish prerenal azotemia (dehydration, >20:1) from intrinsic kidney disease (<10:1).' WHERE name = 'BUN/Creatinine Ratio' AND description IS NULL;
UPDATE metrics SET description = 'Glucose detected in urine; normally absent because kidneys reabsorb all filtered glucose; present in uncontrolled diabetes (blood glucose exceeds renal threshold ~180 mg/dL).' WHERE name = 'Glucose, Urine' AND description IS NULL;
UPDATE metrics SET description = 'Ketone bodies in urine — products of fat breakdown when cells cannot use glucose; seen in diabetic ketoacidosis, prolonged fasting, low-carbohydrate diets, or starvation.' WHERE name = 'Ketones, Urine' AND description IS NULL;
UPDATE metrics SET description = 'Measure of urine concentration relative to pure water; reflects the kidney''s ability to concentrate urine; low in diabetes insipidus or excessive fluid intake, high in dehydration.' WHERE name = 'Specific Gravity, Urine' AND description IS NULL;
UPDATE metrics SET description = 'Acidity of urine; normally 4.5–8.0 and varies widely with diet and acid-base status; alkaline urine can indicate urinary tract infection with urease-producing bacteria.' WHERE name = 'Urine pH' AND description IS NULL;
UPDATE metrics SET description = 'Immature red blood cells just released from bone marrow — the reticulocyte count reflects how actively the bone marrow is producing RBCs; elevated in hemolysis or acute blood loss.' WHERE name = 'Reticulocyte Count' AND description IS NULL;
UPDATE metrics SET description = 'Immature red blood cells still containing a nucleus; normally absent from adult peripheral blood; seen in severe anemia, bone marrow stress, or myelophthisic processes.' WHERE name = 'Nucleated RBC' AND description IS NULL;
UPDATE metrics SET description = 'Estimated average plasma glucose derived from HbA1c; provides an intuitive mg/dL equivalent of the glycated hemoglobin result for patient counseling.' WHERE name = 'Mean Plasma Glucose' AND description IS NULL;
