apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    uid: postgres
    url: postgres:5432
    database: health_tracker
    user: health
    secureJsonData:
      password: health
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
